### ISSUE TITLE
Test failure in 40_oo.t

### ISSUE THREAD

**Issue by racke** [sympa-community/p5-sympatic#2]
```
racke@belukha:~/sympa-community/p5-sympatic$ prove -vl t/40_oo.t 
t/40_oo.t .. 
ok 1 - $p is a ref to Person (Person)
Can't locate object method "lastname" via package "Person" at t/40_oo.t line 28.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 1.
Dubious, test returned 255 (wstat 65280, 0xff00)
All 1 subtests passed 

Test Summary Report
-------------------
t/40_oo.t (Wstat: 65280 Tests: 1 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=1, Tests=1,  0 wallclock secs ( 0.01 usr  0.00 sys +  0.09 cusr  0.00 csys =  0.10 CPU)
Result: FAIL

```

**Comment by eiro** [comment]
hello racke and thanks for the report.

this is output from the command you gave using the last sympatic commit so before i investigate, can you test again with at least  d829293 ?

prove -v t/40_oo.t  
t/40_oo.t .. 
ok 1 - $p is a ref to Person (Person)
ok 2 - ->lastname  from constructor
ok 3 -  not defined $p->firstname 
ok 4 - ->firstname from //=
ok 5 - ->firstname existed
ok 6 - ->age = 42
ok 7 - ->age = 43
1..7
ok
All tests successful.
Files=1, Tests=7,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.13 cusr  0.00 csys =  0.16 CPU)
Result: PASS

**Comment by racke** [comment]
Yes it works now.

**Comment by eiro** [comment]
interesting: i still have the problem when i run the test suite in a docker or in the CI

**Comment by racke** [comment]
Your construct for "package Person" in the test file seems really odd to me. Get rid of the eval there. Also all the eval stuff is really uncommon too. There are way more testing functions than "is" and "ok" as well - like use_ok, can_ok, isa_ok ....

**Comment by eiro** [comment]
hello

On Wed, Feb 28, 2018 at 09:40:59AM +0000, Stefan Hornburg (Racke) wrote:
> Your construct for "package Person" in the test file seems really odd
> to me. Get rid of the eval there. Also all the eval stuff is really
> uncommon too. There are way more testing functions than "is" and "ok"
> as well - like use_ok, can_ok, isa_ok ....

ok. i'll try another way but i really would like to know why it is
working in some cases only.

thanks and regards

**Comment by eiro** [comment]
https://github.com/sympa-community/p5-sympatic/commit/1247bfa2950cd72f734e825a1298e4f6d57c4f98 fixes that. thanks
